# Site settings
title:       The Code Apprentice
email:       karlav.jaramillo@gmail.com
author:      Karla Jaramillo
description: "Simple and lovely tutorials, a learning process to boost my programming path."
baseurl:     ""
home:        "/"
url:         "http://karlajaramillo.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  false
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: 

# Social icons
github_username:
stackoverflow_id:
twitter_username: kavajaga
google_plus_id:
linkedin_username: karlavjaramillo
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: true
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
